PROJECT_NAME := MyUefiFw

ARCH       ?= X64
TOOLCHAIN  ?= GCC
BUILD_TYPE ?= DEBUG

PLATFORM := MyUefiFwPkg/MyUefiFw.dsc

PROJECT_ROOT := $(CURDIR)
EDK2_ROOT    := $(abspath $(PROJECT_ROOT)/../edk2)

EDK2_WRAPPER := $(PROJECT_ROOT)/scripts/edk2.sh

#
# EDK II internal build directory
#
EDK2_BUILD_DIR := $(EDK2_ROOT)/Build/$(PROJECT_NAME)/$(BUILD_TYPE)_$(TOOLCHAIN)
EDK2_FV_DIR    := $(EDK2_BUILD_DIR)/FV

EDK2_CODE_FD := $(EDK2_FV_DIR)/MYUEFIFW_CODE.fd
EDK2_VARS_FD := $(EDK2_FV_DIR)/MYUEFIFW_VARS.fd
EDK2_FULL_FD := $(EDK2_FV_DIR)/MYUEFIFW.fd

#
# Project-visible build artifacts
#
BUILD_DIR := $(PROJECT_ROOT)/build

CODE_FD := $(BUILD_DIR)/MYUEFIFW_CODE.fd
VARS_FD := $(BUILD_DIR)/MYUEFIFW_VARS.fd
FULL_FD := $(BUILD_DIR)/MYUEFIFW.fd

#
# Writable UEFI variable store used by QEMU.
# This file is intentionally NOT overwritten by normal builds.
#
RUNTIME_VARS_FD := $(BUILD_DIR)/MYUEFIFW_VARS.runtime.fd

DEBUG_LOG := $(BUILD_DIR)/debug.log


.PHONY: all build run reset-vars clean distclean debug release

all: build


#
# Build firmware using EDK II and export final firmware images
# into this repository's build/ directory.
#
build:
	$(EDK2_WRAPPER) build \
		-a $(ARCH) \
		-t $(TOOLCHAIN) \
		-b $(BUILD_TYPE) \
		-p $(PLATFORM)

	mkdir -p $(BUILD_DIR)

	cp $(EDK2_CODE_FD) $(CODE_FD)
	cp $(EDK2_VARS_FD) $(VARS_FD)
	cp $(EDK2_FULL_FD) $(FULL_FD)

	@echo
	@echo "Firmware artifacts:"
	@ls -lh $(BUILD_DIR)/*.fd


#
# Run firmware in QEMU.
#
# CODE_FD is used directly.
# RUNTIME_VARS_FD is writable and persists between runs.
#
run: build
	@if [ ! -f "$(RUNTIME_VARS_FD)" ]; then \
		echo "Creating runtime UEFI variable store..."; \
		cp "$(VARS_FD)" "$(RUNTIME_VARS_FD)"; \
	fi

	rm -f $(DEBUG_LOG)

	qemu-system-x86_64 \
		-machine q35 \
		-m 512M \
		-drive if=pflash,format=raw,readonly=on,file=$(CODE_FD) \
		-drive if=pflash,format=raw,file=$(RUNTIME_VARS_FD) \
		-debugcon file:$(DEBUG_LOG) \
		-global isa-debugcon.iobase=0x402


#
# Reset QEMU NVRAM to the pristine image generated by the build.
#
reset-vars: build
	cp -f $(VARS_FD) $(RUNTIME_VARS_FD)
	@echo "UEFI variable store reset."


#
# Remove this project's exported artifacts.
#
clean:
	rm -rf $(BUILD_DIR)


#
# Also remove EDK II intermediate build output.
#
distclean: clean
	rm -rf $(EDK2_ROOT)/Build/$(PROJECT_NAME)


debug:
	$(MAKE) BUILD_TYPE=DEBUG build


release:
	$(MAKE) BUILD_TYPE=RELEASE build
